remote_theme: Minimal theme
url: merlin761.github.io
title: Welcome to Merlin homepage !
description: This is my ePotfolio for my CS-499-17487-M01 Computer Science Capstone !
show_downloads: false
google_analytics: "GTM-PTHS2KL"
